POST http://localhost:3001/api/notes/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBpbHBwaWxvcHBpcyIsImlkIjoiNWY5NTUxNzY3NjAxZmUzMTA0ZDNhZDQwIiwiaWF0IjoxNjAzNzE2NDU4fQ.owAwk9nlS1zuOrJZbd1agApw1u9lHNCRTJg_M6-7M7g

{
    "content": "Test refactored authorization middleware",
    "important": true
}